FROM alpine

MAINTAINER Doyle Fermi <doylefermi@gmail.com>
RUN apk add --update bash
RUN apk add --update curl 
RUN apk add --update bc
RUN apk add --update bash
RUN rm -rf /var/cache/apk/*
WORKDIR /tmp
